
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Adhwa
 */
public class Formkelas extends javax.swing.JFrame {

    /**
     * Creates new form tabelkelas
     */
    public JTextField tampilidkelas = new javax.swing.JTextField();
    public JTextField tnisnsiswa = new javax.swing.JTextField();
    public JTextField tnissiswa = new javax.swing.JTextField();
    public JTextField tnamasiswa = new javax.swing.JTextField();
    public JTextField tampidspp = new javax.swing.JTextField();
    public JPanel mainpanel = new javax.swing.JPanel();
    public JPanel Psiswa = new javax.swing.JPanel();
    private Connection con = new koneksi().connect();

    public Formkelas() {
        initComponents();
        tablekelas();
    }
    String tnisn = tnisnsiswa.getText();
    String tnis = tnissiswa.getText();
    String tnama = tnamasiswa.getText();

    public void tablekelas() {
        DefaultTableModel tbkelas = new DefaultTableModel();
        tbkelas.addColumn("Id Kelas");
        tbkelas.addColumn("Nama Kelas");
        tbkelas.addColumn("Kompetensi Keahlian");

        try {
            String sql = "SELECT * FROM kelas";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                tbkelas.addRow(new Object[]{
                    rs.getString("Id_kelas"),
                    rs.getString("nama_kelas"),
                    rs.getString("kompetensi_keahlian")});
                tabelkelas2.setModel(tbkelas);
            }
//            JOptionPane.showMessageDialog(null, "Koneksi berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi gagal" + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelkelas2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelkelas2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID SPP", "Tahun", "Nominal"
            }
        ));
        tabelkelas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelkelas2MouseClicked(evt);
            }
        });
        tabelkelas2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelkelas2KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelkelas2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelkelas2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelkelas2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelkelas2KeyPressed

    private void tabelkelas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelkelas2MouseClicked
        tampilan sis = new tampilan();

        TableModel tm = tabelkelas2.getModel();
        sis.mainpanel.add(Psiswa).setVisible(true);
        String idkelas = (tm.getValueAt(tabelkelas2.getSelectedRow(), 0).toString());
        System.out.println(tnisn);
        System.out.println(tnis);
        sis.tnisnsiswa.setText(tnisn);
        sis.tnissiswa.setText(tnis);
        sis.tnamasiswas.setText(tnama);
        sis.tampilidkelas.setText(idkelas);
//        sis.mainpanel.removeAll();
//        sis.mainpanel.repaint();
//        sis.mainpanel.revalidate();
//
//        sis.mainpanel.add(sis.Psiswa);
//        sis.mainpanel.repaint();
//        sis.mainpanel.revalidate();

        this.dispose();
    }//GEN-LAST:event_tabelkelas2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formkelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formkelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formkelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formkelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formkelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabelkelas2;
    // End of variables declaration//GEN-END:variables
}
