
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListCellRenderer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Adhwa
 */
public class Loginadmin1 extends javax.swing.JFrame {

    public JButton btest = new javax.swing.JButton();
    public JLabel siswa = new javax.swing.JLabel();
//    panel siswa
    public JLabel greating = new javax.swing.JLabel();
//    panel petugas
    public JLabel bpetugas = new javax.swing.JLabel();
    public JLabel bspp = new javax.swing.JLabel();
    public JLabel bkelas = new javax.swing.JLabel();

//    panel spp
    public JButton bsimpanspp = new javax.swing.JButton();
    public JButton beditspp = new javax.swing.JButton();
    public JButton bhapusspp = new javax.swing.JButton();

//    koneksi
    private Connection conn = new koneksi().connect();

    public Loginadmin1() {
        initComponents();
        clevel.setRenderer(new DefaultListCellRenderer() {
            @Override
            public void paint(Graphics g) {
                setBackground(Color.WHITE);
                setForeground(Color.BLACK);
                super.paint(g);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        tombol = new javax.swing.JLabel();
        asli = new javax.swing.JLabel();
        tuser1 = new javax.swing.JTextField();
        salah = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        tpass = new javax.swing.JPasswordField();
        clevel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        hover = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tombol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolMouseClicked(evt);
            }
        });
        getContentPane().add(tombol, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 160, 30));

        asli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/icons8-close-window-30.png"))); // NOI18N
        asli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asliMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                asliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                asliMouseExited(evt);
            }
        });
        getContentPane().add(asli, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 50, 50));

        tuser1.setBackground(new java.awt.Color(255, 255, 255, 0));
        tuser1.setText("enter username");
        tuser1.setBorder(null);
        tuser1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tuser1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tuser1FocusLost(evt);
            }
        });
        tuser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuser1ActionPerformed(evt);
            }
        });
        tuser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tuser1KeyPressed(evt);
            }
        });
        getContentPane().add(tuser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 170, 30));

        salah.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(salah, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 150, 20));

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("lihat password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 110, -1));

        tpass.setBackground(new java.awt.Color(255, 255, 255, 0));
        tpass.setText("masukan password");
        tpass.setToolTipText("");
        tpass.setBorder(null);
        tpass.setEchoChar('\u25cf');
        tpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tpassFocusGained(evt);
            }
        });
        tpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpassActionPerformed(evt);
            }
        });
        tpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tpassKeyPressed(evt);
            }
        });
        getContentPane().add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 170, 30));

        clevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "admin", "petugas" }));
        clevel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clevelFocusGained(evt);
            }
        });
        clevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clevelActionPerformed(evt);
            }
        });
        getContentPane().add(clevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 180, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/icons8-back-arrow-30.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        hover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/icons8-close-window-30 (2).png"))); // NOI18N
        hover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hoverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverMouseExited(evt);
            }
        });
        getContentPane().add(hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 50, 50));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lupa password");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/background buat siswa.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 402));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tuser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuser1ActionPerformed

    }//GEN-LAST:event_tuser1ActionPerformed

    private void asliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asliMouseClicked
        this.dispose();
    }//GEN-LAST:event_asliMouseClicked

    private void tombolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolMouseClicked
        String level = clevel.getSelectedItem().toString();

        if (tuser1.getText().trim().isEmpty() || tpass.getText().trim().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "masih ada kolom yang kosong bestiee");
            tuser1.setText("username kosong");
            tuser1.setText("password kosong");

        } else if (tuser1.getText().trim().isEmpty()) {
            tuser1.setText("username kosong");
        }
        try {

            String sql = "SELECT * FROM petugas WHERE username ='" + tuser1.getText() + "' and password='" + tpass.getText() + "' and level='" + level + "';";

            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                String id = rs.getString("id_petugas");
                String username = rs.getString("username");
                String nama = rs.getString("nama_petugas");
                String levelpet = rs.getString("level");

                //set user data session
                userSession.set_id(id);
                userSession.set_username(username);
                userSession.set_nama(nama);
                userSession.set_level(levelpet);
                if (levelpet.equals("admin")) {
                    tampilan menu = new tampilan();
//                    menu.siswa.setEnabled( false);
                    menu.greating.setText("Selamat Datang Admin Ku  " + rs.getString(4));

                    menu.setVisible(true);
                    this.dispose();

//                    menu.namauser.setText(rs.getString(2));
                } else if (levelpet.equals("petugas")) {
                    tampilan menu1 = new tampilan();
                    menu1.bpetugas.setVisible(false);
                    menu1.bspp.setVisible(false);
                    menu1.bkelas.setVisible(false);
                    menu1.siswa.setVisible(false);

                    menu1.bsimpanspp.setVisible(false);
                    menu1.beditspp.setVisible(false);
                    menu1.bhapusspp.setVisible(false);
                    menu1.greating.setText("Halooo " + rs.getString(2));
                    menu1.setVisible(true);
                    this.dispose();
                }
            } else if (!rs.next()) {
                JOptionPane.showMessageDialog(rootPane, "Login Gagal", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException ex) {
            System.out.println("User Tidak ditemukan");

        }
    }//GEN-LAST:event_tombolMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            tpass.setEchoChar((char) 0);
        } else {
            tpass.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void tpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpassActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new tampilan_awal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void tuser1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tuser1FocusGained
        if (tuser1.getText().equals("enter username")) {
            tuser1.setText("");
        }
    }//GEN-LAST:event_tuser1FocusGained

    private void tuser1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tuser1FocusLost
        if (tuser1.getText().equals("")) {
            tuser1.setText("enter username");
        }
    }//GEN-LAST:event_tuser1FocusLost

    private void hoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverMouseClicked
        this.dispose();
    }//GEN-LAST:event_hoverMouseClicked

    private void asliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asliMouseEntered
        asli.setVisible(false);
        asli.setEnabled(false);
        hover.setEnabled(true);
        hover.setOpaque(true);
//        hover.setBackground(Color.lightGray);
    }//GEN-LAST:event_asliMouseEntered

    private void hoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverMouseEntered

    }//GEN-LAST:event_hoverMouseEntered

    private void hoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverMouseExited

    }//GEN-LAST:event_hoverMouseExited

    private void asliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asliMouseExited
        asli.setVisible(true);
        asli.setEnabled(true);
        hover.setEnabled(true);
        hover.setBackground(new Color(217, 217, 217, 128)); // mengatur latar belakang label dengan transparansi 50%
        hover.setOpaque(false);
    }//GEN-LAST:event_asliMouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setForeground(new Color(217, 217, 217, 128));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabel2MouseExited

    private void tpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tpassFocusGained
        if (tpass.getText().equals("masukan password")) {
            tpass.setText("");
        }
    }//GEN-LAST:event_tpassFocusGained

    private void clevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clevelActionPerformed

    private void tuser1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tuser1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tpass.requestFocus();
        }
    }//GEN-LAST:event_tuser1KeyPressed

    private void tpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            clevel.requestFocus();
        }
    }//GEN-LAST:event_tpassKeyPressed

    private void clevelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clevelFocusGained
         clevel.showPopup();
    }//GEN-LAST:event_clevelFocusGained

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginadmin1.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginadmin1.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginadmin1.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginadmin1.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginadmin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asli;
    private javax.swing.JComboBox<String> clevel;
    private javax.swing.JLabel hover;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel salah;
    private javax.swing.JLabel tombol;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tuser1;
    // End of variables declaration//GEN-END:variables
}
