
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Adhwa
 */
public class loginbaru extends javax.swing.JFrame {

    public JLabel namausersis = new javax.swing.JLabel();
    public JLabel tampilnis1 = new javax.swing.JLabel();
    public JLabel tampilnama1 = new javax.swing.JLabel();
    public JLabel tampilid = new javax.swing.JLabel();

    /**
     * Creates new form loginbaru
     */
    private Connection conn = new koneksi().connect();

    public loginbaru() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tuse = new javax.swing.JTextField();
        tpass = new javax.swing.JPasswordField();
        salahpass = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        salahuser = new javax.swing.JLabel();
        simpan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tuse.setBackground(new java.awt.Color(255,255,255,0)
        );
        tuse.setBorder(null);
        tuse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuseActionPerformed(evt);
            }
        });
        tuse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tuseKeyReleased(evt);
            }
        });
        getContentPane().add(tuse, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 170, 30));

        tpass.setBackground(new java.awt.Color(255,255,255,0));
        tpass.setBorder(null);
        tpass.setEchoChar('\u25cf');
        tpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpassActionPerformed(evt);
            }
        });
        getContentPane().add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 180, 30));

        salahpass.setForeground(new java.awt.Color(255, 102, 102));
        salahpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salahpassMouseClicked(evt);
            }
        });
        getContentPane().add(salahpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 180, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adhwa\\Downloads\\icons8-close-window-30.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, 40));

        salahuser.setForeground(new java.awt.Color(255, 102, 102));
        salahuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salahuserMouseClicked(evt);
            }
        });
        getContentPane().add(salahuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 170, 30));

        simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 170, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/icons8-back-arrow-30.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        cbox.setForeground(new java.awt.Color(255, 255, 255));
        cbox.setText("Show Password");
        cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxActionPerformed(evt);
            }
        });
        getContentPane().add(cbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/background form login.png"))); // NOI18N
        jLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel1PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tuseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuseActionPerformed

    private void jLabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1PropertyChange

    private void tpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpassActionPerformed
//        tpass.addKeyListener(new KeyAdapter() {
//            @Override
//            public void keyPressed(KeyEvent e) {
//                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
//                    simpan.;
//                }
//            }
//        });

    }//GEN-LAST:event_tpassActionPerformed

    private void salahpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salahpassMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salahpassMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void salahuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salahuserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_salahuserMouseClicked

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        if (tuse.getText().trim().isEmpty() || tpass.getText().trim().isEmpty()) {

//            JOptionPane.showMessageDialog(null, "masih ada kolom yang kosong bestiee");
            salahuser.setText("username kosong");
            salahpass.setText("password kosong");

        } else if (tuse.getText().trim().isEmpty()) {
            salahuser.setText("username kosong");
        }
        try {
            String sql = "Select * from siswa where nisn ='" + tuse.getText() + "' and nis='" + tpass.getText() + "';";

            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
//                new tampilan_siswa().setVisible(true);
//                String id = rs.getString("nisn");
//                String nis = rs.getString("nis");
//                String nama = rs.getString("nama");
//                String levelpet = rs.getString("level");
//
//                //set user data session
//                userSession.set_id(id);
//                userSession.set_username(nis);
//                userSession.set_nama(nama);
//                userSession.set_level(levelpet);
                this.dispose();
                tampilan_siswa menu1 = new tampilan_siswa();
                menu1.namausersis.setText("Selamat Datang " + rs.getString(3) + "!!!");
                menu1.tampilnisn.setText(rs.getString(0));
                menu1.tampilnama1.setText(rs.getString(3));
                menu1.tampilid.setText(rs.getString(4));
//                menu1.tampiltabelhistoripembayaransiswa();

                menu1.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(rootPane, "User Tidak Ditemukan");
                JOptionPane.showMessageDialog(rootPane, ERROR);
                tuse.setText("");
                tpass.setText("");
            }

        } catch (SQLException ex) {
            System.out.println("User Tidak ditemukan");

        }

    }//GEN-LAST:event_simpanMouseClicked

    private void tuseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tuseKeyReleased
        salahuser.setText("");
        salahpass.setText("");
    }//GEN-LAST:event_tuseKeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new tampilan_awal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxActionPerformed
        if (cbox.isSelected()) {
            tpass.setEchoChar((char) 0);
        } else {
            tpass.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_cboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginbaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginbaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginbaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginbaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginbaru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel salahpass;
    private javax.swing.JLabel salahuser;
    private javax.swing.JLabel simpan;
    private javax.swing.JPasswordField tpass;
    public javax.swing.JTextField tuse;
    // End of variables declaration//GEN-END:variables
}
