
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Adhwa
 */
public class tampilan_awal extends javax.swing.JFrame {

    /**
     * Creates new form tampilan_awal
     */
    public tampilan_awal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SISWA = new javax.swing.JLabel();
        SISWA1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SISWA.setBackground(new java.awt.Color(204, 204, 204));
        SISWA.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        SISWA.setForeground(new java.awt.Color(255, 255, 255));
        SISWA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SISWA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/icons8-administrator-male-25.png"))); // NOI18N
        SISWA.setText("ADMIN");
        SISWA.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));
        SISWA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SISWA.setOpaque(true);
        SISWA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SISWAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SISWAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SISWAMouseExited(evt);
            }
        });
        getContentPane().add(SISWA, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 140, 40));

        SISWA1.setBackground(new java.awt.Color(204, 204, 204));
        SISWA1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        SISWA1.setForeground(new java.awt.Color(255, 255, 255));
        SISWA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SISWA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/icons8-student-25.png"))); // NOI18N
        SISWA1.setText("SISWA");
        SISWA1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));
        SISWA1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SISWA1.setOpaque(true);
        SISWA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SISWA1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SISWA1MouseEntered(evt);
            }
        });
        getContentPane().add(SISWA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/halaman_awal_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SISWAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SISWAMouseEntered
        SISWA.setBackground(new Color(128, 128, 128));
    }//GEN-LAST:event_SISWAMouseEntered

    private void SISWA1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SISWA1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SISWA1MouseEntered

    private void SISWAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SISWAMouseClicked
        new loginbuatuser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SISWAMouseClicked

    private void SISWA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SISWA1MouseClicked
        new loginbaru().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SISWA1MouseClicked

    private void SISWAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SISWAMouseExited
        
    }//GEN-LAST:event_SISWAMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilan_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilan_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilan_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilan_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilan_awal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SISWA;
    private javax.swing.JLabel SISWA1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
